@startuml
note over LQMgr: state - WaitForNotify
PSCAgent -> LQMgr: Notify(event_type, event)

note over LQMgr: state: GetRequests
LQMgr -> LQTimeStampKeeper: GetCurrentTimeStamp()
LQTimeStampKeeper -> LQMgr: currentTimeStamp

LQMgr -> LQHttpEngine: GetRequest(currentTimeStamp)
LQHttpEngine -> LQRequestGetter: Get(currentTimeStamp)
LQRequestGetter -> LQHttpEngine : lqRequests

LQHttpEngine -> LQMgr: lqRequests

LQMgr -> LQTimeStampKeeper : UpdateKeeperNewRequestTimeStamp(lqRequests)

note over LQMgr: state: ProcessGetResponse\nRunNextQuery\nSendResult
    loop for_each lqRequest
        LQMgr -> LQRunner: Run(lqRequest)
        LQRunner -> LQMgr : lqResult
        LQMgr -> LQHttpEngine : SendResult(lqResult)
        LQHttpEngine -> LQResultSender: Send(lqResult)
        LQMgr -> LQTimeStampKeeper : ProcessedQuery(lqResult)
    end

participant PSCAgent order 10
participant LQMgr order 20
participant LQTimeStampKeeper order 30
participant LQRunner order 40
participant LQHttpEngine order 50
participant LQRequestGetter order 60
participant LQResultSender order 70

@enduml