@startuml
PSCAgent -> LQMgr: Notify(event_type, event)

LQMgr -> LQTimeStampKeeper: GetCurrentTimeStamp()
LQTimeStampKeeper -> LQMgr: currentTimeStamp

LQMgr -> LQHttpEngine: EnqueueGetRequest(currentTimeStamp)
LQHttpEngine -> LQRequestGetter: Get(currentTimeStamp)
LQRequestGetter -> LQHttpEngine : lqRequests

LQHttpEngine -> LQMgr: NewQueries(lqRequests)

LQMgr -> LQTimeStampKeeper : NewQueries(lqRequests)

    loop for_each lqRequest
        LQMgr -> LQRunner: Enqueue(lqRequest)
    end

LQRunner -> LQMgr : CompletedQuery(lqRequest, lqResult)

LQMgr -> LQHttpEngine : EnqueueSendResult(lqResult)
LQHttpEngine -> LQResultSender : Send(lqResult)
LQResultSender -> LQHttpEngine : ResultSent(lqResult)
LQHttpEngine -> LQMgr : ResultSent(lqResult)

LQMgr -> LQTimeStampKeeper : ProcessedQuery(lqRequest)

@enduml